'use client';

import Link from 'next/link';
import { Bell, CheckCheck, Radio, Trash2 } from 'lucide-react';
import type { ReactNode } from 'react';
import { AppCard, Badge, EmptyState, Loading, PageHeader } from '@/shared/ui/components';
import { useNotificationCenter, useNotificationPreferences } from './hooks';
import type { NotificationFilterValue, NotificationRecord, NotificationRole } from './types';

const filters: { label: string; value: NotificationFilterValue }[] = [
  { label: 'All', value: 'all' }, { label: 'Unread', value: 'unread' }, { label: 'Read', value: 'read' },
  { label: 'Booking', value: 'booking' }, { label: 'Payment', value: 'payment' }, { label: 'Ticket', value: 'ticket' },
  { label: 'Driver', value: 'driver' }, { label: 'Trip', value: 'trip' }, { label: 'Promo', value: 'promo' },
  { label: 'Membership', value: 'membership' }, { label: 'System', value: 'system' },
];

export function NotificationCenter({ role }: { role: NotificationRole }) {
  const center = useNotificationCenter(role);
  return <div className="space-y-6"><NotificationHeader role={role} unread={center.unread} onMarkAllRead={center.markAllRead} realtimeConnected={center.realtime.connected} realtimeEnabled={center.realtime.enabled} /><NotificationTabs unread={center.unread} total={center.items.length} /><div className="grid gap-6 lg:grid-cols-[18rem_1fr]"><aside className="space-y-4"><NotificationSearch value={center.query} onChange={center.setQuery} /><NotificationFilter value={center.filter} onChange={center.setFilter} /><NotificationCounter unread={center.unread} total={center.items.length} /></aside><section className="space-y-4"><NotificationList items={center.paged} onOpen={center.setSelected} onMarkRead={center.markRead} onMarkUnread={center.markUnread} onDelete={center.deleteOne} /><NotificationPagination page={center.page} pageCount={center.pageCount} onPage={center.setPage} /></section></div><NotificationDrawer notification={center.selected} onClose={() => center.setSelected(null)} onMarkRead={center.markRead} onMarkUnread={center.markUnread} onDelete={center.deleteOne} /></div>;
}

export function NotificationHeader({ role, unread, onMarkAllRead, realtimeConnected, realtimeEnabled }: { role: NotificationRole; unread: number; onMarkAllRead: () => void; realtimeConnected: boolean; realtimeEnabled: boolean }) { return <PageHeader title="Notification Center" description={`Shared ${role} inbox for notification APIs and Reverb realtime events.`} actions={<div className="flex flex-wrap gap-2"><RealtimeStatusIndicator connected={realtimeConnected} enabled={realtimeEnabled} /><button onClick={onMarkAllRead} className="rounded-2xl bg-primary px-4 py-2 text-sm font-bold text-white"><CheckCheck size={16} className="mr-2 inline" />Mark all read ({unread})</button><Link className="rounded-2xl border border-slate-200 px-4 py-2 text-sm font-bold dark:border-slate-800" href="/settings/notifications">Settings</Link></div>} />; }
export function NotificationTabs({ unread, total }: { unread: number; total: number }) { return <div className="flex flex-wrap gap-2"><Badge tone="neutral">All {total}</Badge><NotificationBadge unread={unread} /><Badge tone="success">Read {Math.max(total - unread, 0)}</Badge></div>; }
export function NotificationBadge({ unread }: { unread: number }) { return <Badge tone={unread ? 'danger' : 'success'}>{unread ? `Unread ${unread}` : 'All read'}</Badge>; }
export function NotificationCounter({ unread, total }: { unread: number; total: number }) { return <AppCard><p className="text-sm font-bold text-slate-500">Unread counter</p><p className="mt-2 text-3xl font-extrabold">{unread}</p><p className="text-sm text-slate-500">{total} total notifications</p></AppCard>; }
export function NotificationSearch({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="block rounded-2xl border border-slate-200 bg-white p-3 text-sm dark:border-slate-800 dark:bg-slate-900"><span className="font-bold">Search</span><input value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full bg-transparent outline-none" placeholder="Search title, message, entity" /></label>; }
export function NotificationFilter({ value, onChange }: { value: NotificationFilterValue; onChange: (value: NotificationFilterValue) => void }) { return <AppCard className="space-y-2"><p className="text-sm font-bold text-slate-500">Filter</p>{filters.map((filter) => <button key={filter.value} onClick={() => onChange(filter.value)} className={`mr-2 mt-2 rounded-full px-3 py-1 text-xs font-bold ${value === filter.value ? 'bg-primary text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>{filter.label}</button>)}</AppCard>; }

export function NotificationList(props: { items: NotificationRecord[]; onOpen: (item: NotificationRecord) => void; onMarkRead: (id: string) => void; onMarkUnread: (id: string) => void; onDelete: (id: string) => void }) { if (!props.items.length) return <NotificationEmptyState />; return <div className="space-y-3">{props.items.map((item) => <NotificationCard key={item.id} {...props} item={item} />)}</div>; }
export function NotificationCard({ item, onOpen, onMarkRead, onMarkUnread, onDelete }: { item: NotificationRecord; onOpen: (item: NotificationRecord) => void; onMarkRead: (id: string) => void; onMarkUnread: (id: string) => void; onDelete: (id: string) => void }) { return <NotificationItem item={item} onOpen={onOpen} actions={<NotificationActions notification={item} onMarkRead={onMarkRead} onMarkUnread={onMarkUnread} onDelete={onDelete} />} />; }
export function NotificationItem({ item, onOpen, actions }: { item: NotificationRecord; onOpen: (item: NotificationRecord) => void; actions: ReactNode }) { return <AppCard className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><button onClick={() => onOpen(item)} className="text-left"><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-lg font-bold">{item.title}</h2><StatusBadge status={item.status} /><Badge>{item.category}</Badge></div><p className="mt-1 text-sm text-slate-500">{item.message}</p><p className="mt-2 text-xs font-bold text-slate-400">{new Date(item.timestamp).toLocaleString()}</p></button>{actions}</AppCard>; }
export function StatusBadge({ status }: { status: NotificationRecord['status'] }) { return <Badge tone={status === 'unread' ? 'warning' : 'success'}>{status}</Badge>; }
export function NotificationActions({ notification, onMarkRead, onMarkUnread, onDelete }: { notification: NotificationRecord; onMarkRead: (id: string) => void; onMarkUnread: (id: string) => void; onDelete: (id: string) => void }) { return <div className="flex flex-wrap gap-2"><button className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold dark:bg-slate-800" onClick={() => notification.status === 'read' ? onMarkUnread(notification.id) : onMarkRead(notification.id)}>{notification.status === 'read' ? 'Mark Unread' : 'Mark Read'}</button><button className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700" onClick={() => onDelete(notification.id)}><Trash2 size={14} className="mr-1 inline" />Delete</button></div>; }
export function NotificationDrawer({ notification, onClose, onMarkRead, onMarkUnread, onDelete }: { notification: NotificationRecord | null; onClose: () => void; onMarkRead: (id: string) => void; onMarkUnread: (id: string) => void; onDelete: (id: string) => void }) { return notification ? <div className="fixed inset-0 z-50 bg-slate-950/30 p-4" onClick={onClose}><aside className="ml-auto h-full w-full max-w-xl overflow-auto rounded-3xl bg-white p-6 shadow-soft dark:bg-slate-950" onClick={(event) => event.stopPropagation()}><NotificationDetail notification={notification} /><div className="mt-6"><NotificationActions notification={notification} onMarkRead={onMarkRead} onMarkUnread={onMarkUnread} onDelete={onDelete} /></div><button className="mt-6 text-sm font-bold text-slate-500" onClick={onClose}>Close</button></aside></div> : null; }
export function NotificationDetail({ notification }: { notification: NotificationRecord }) { return <div className="space-y-4"><Bell /><h2 className="font-display text-2xl font-bold">{notification.title}</h2><p className="text-slate-600 dark:text-slate-300">{notification.message}</p><StatusBadge status={notification.status} /><p className="text-sm text-slate-500">Timestamp: {new Date(notification.timestamp).toLocaleString()}</p>{notification.relatedEntity ? <p className="text-sm font-bold">Related entity: {notification.relatedEntity.href ? <Link className="text-primary" href={notification.relatedEntity.href}>{notification.relatedEntity.label}</Link> : notification.relatedEntity.label}</p> : null}{notification.action?.href ? <Link className="inline-flex rounded-2xl bg-primary px-4 py-2 text-sm font-bold text-white" href={notification.action.href}>{notification.action.label}</Link> : null}</div>; }
export function NotificationEmptyState() { return <EmptyState title="No notifications" description="New matching notifications will appear here." />; }
export function NotificationLoading() { return <Loading />; }
export function NotificationPagination({ page, pageCount, onPage }: { page: number; pageCount: number; onPage: (page: number) => void }) { return <div className="flex items-center justify-end gap-2"><button disabled={page <= 1} onClick={() => onPage(page - 1)} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold disabled:opacity-50 dark:bg-slate-800">Previous</button><span className="text-sm font-bold">Page {page} / {pageCount}</span><button disabled={page >= pageCount} onClick={() => onPage(page + 1)} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold disabled:opacity-50 dark:bg-slate-800">Next</button></div>; }
export function RealtimeStatusIndicator({ connected, enabled }: { connected: boolean; enabled: boolean }) { return <span className="inline-flex items-center gap-2 rounded-2xl bg-slate-100 px-4 py-2 text-sm font-bold dark:bg-slate-800"><Radio size={16} className={connected ? 'text-success' : 'text-warning'} />{enabled ? (connected ? 'Realtime connected' : 'Realtime connecting') : 'Realtime disabled'}</span>; }

export function NotificationPreference() { const { preferences, toggle } = useNotificationPreferences(); return <div className="space-y-6"><PageHeader title="Notification Settings" description="Enable or disable notification categories and delivery placeholders without changing backend flow." /><AppCard className="divide-y divide-slate-100 dark:divide-slate-800">{preferences.map((preference) => <label key={preference.key} className="flex items-center justify-between gap-4 py-4"><span><span className="font-bold">{preference.label}</span>{preference.placeholder ? <span className="ml-2 text-xs font-bold text-slate-400">placeholder</span> : null}</span><input type="checkbox" checked={preference.enabled} onChange={() => toggle(preference.key)} className="h-5 w-5" /></label>)}</AppCard></div>; }
