<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->string('name'); $table->string('email')->unique(); $table->timestamp('email_verified_at')->nullable(); $table->string('password'); $table->string('role')->index(); $table->json('metadata')->nullable(); $table->rememberToken(); $table->timestamps(); });
        Schema::create('customers', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->string('phone')->index(); $table->date('birth_date')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('drivers', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->string('license_number')->unique(); $table->string('status')->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('vehicle_layouts', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->string('name')->unique(); $table->unsignedSmallInteger('capacity'); $table->json('metadata')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('vehicles', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('vehicle_layout_id')->nullable()->constrained()->nullOnDelete(); $table->string('plate_number')->unique(); $table->string('code')->unique(); $table->string('brand'); $table->string('status')->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('vehicle_seats', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('vehicle_id')->constrained()->cascadeOnDelete(); $table->string('seat_number'); $table->string('class')->default('regular'); $table->boolean('is_active')->default(true); $table->timestamps(); $table->softDeletes(); $table->unique(['vehicle_id','seat_number']); });
        Schema::create('seat_maps', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('vehicle_layout_id')->constrained()->cascadeOnDelete(); $table->string('seat_number'); $table->unsignedTinyInteger('row'); $table->unsignedTinyInteger('column'); $table->json('metadata')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('routes', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->string('code')->unique(); $table->string('origin')->index(); $table->string('destination')->index(); $table->unsignedInteger('distance_km'); $table->unsignedInteger('duration_minutes'); $table->timestamps(); $table->softDeletes(); });
        Schema::create('pickup_points', fn(Blueprint $table) => $this->point($table, 'pickup'));
        Schema::create('drop_points', fn(Blueprint $table) => $this->point($table, 'drop'));
        Schema::create('schedules', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('route_id')->constrained()->cascadeOnDelete(); $table->foreignId('driver_id')->constrained()->restrictOnDelete(); $table->foreignId('vehicle_id')->constrained()->restrictOnDelete(); $table->dateTime('departure_at')->index(); $table->dateTime('arrival_at'); $table->decimal('base_fare', 12, 2); $table->string('status')->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('trips', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('schedule_id')->constrained()->cascadeOnDelete(); $table->foreignId('route_id')->constrained()->cascadeOnDelete(); $table->foreignId('driver_id')->constrained()->restrictOnDelete(); $table->foreignId('vehicle_id')->constrained()->restrictOnDelete(); $table->string('status')->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('bookings', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->string('code')->unique(); $table->foreignId('schedule_id')->constrained()->cascadeOnDelete(); $table->foreignId('customer_id')->constrained()->cascadeOnDelete(); $table->string('status')->index(); $table->decimal('amount',12,2); $table->timestamps(); $table->softDeletes(); });
        Schema::create('passengers', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('booking_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->string('identity_number')->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('seat_reservations', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('booking_id')->constrained()->cascadeOnDelete(); $table->foreignId('passenger_id')->constrained()->cascadeOnDelete(); $table->foreignId('vehicle_seat_id')->constrained()->cascadeOnDelete(); $table->string('status')->index(); $table->timestamps(); $table->softDeletes(); $table->unique(['booking_id','vehicle_seat_id']); });
        Schema::create('tickets', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('booking_id')->constrained()->cascadeOnDelete(); $table->string('ticket_number')->unique(); $table->string('qr_code')->unique(); $table->string('status')->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('payments', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('booking_id')->constrained()->cascadeOnDelete(); $table->string('provider')->index(); $table->string('reference')->unique(); $table->decimal('amount',12,2); $table->string('status')->index(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('promos', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->string('code')->unique(); $table->string('name'); $table->decimal('amount',12,2); $table->dateTime('starts_at'); $table->dateTime('ends_at'); $table->timestamps(); $table->softDeletes(); });
        Schema::create('vouchers', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('promo_id')->constrained()->cascadeOnDelete(); $table->string('code')->unique(); $table->boolean('is_active')->default(true); $table->timestamps(); $table->softDeletes(); });
        Schema::create('pricing_rules', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('route_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->decimal('amount',12,2); $table->json('metadata')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('memberships', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('customer_id')->constrained()->cascadeOnDelete(); $table->string('level')->index(); $table->unsignedInteger('points')->default(0); $table->timestamps(); $table->softDeletes(); });
        Schema::create('notifications', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->string('type')->index(); $table->string('title'); $table->text('body'); $table->timestamp('read_at')->nullable(); $table->json('metadata')->nullable(); $table->timestamps(); $table->softDeletes(); });
        Schema::create('activity_logs', function (Blueprint $table): void { $table->id(); $table->uuid('uuid')->unique(); $table->string('action')->index(); $table->string('subject_type')->index(); $table->unsignedBigInteger('subject_id')->nullable(); $table->json('metadata')->nullable(); $table->timestamps(); $table->softDeletes(); });
    }
    private function point(Blueprint $table, string $prefix): void { $table->id(); $table->uuid('uuid')->unique(); $table->foreignId('route_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->string('address'); $table->decimal('latitude',10,7)->nullable(); $table->decimal('longitude',10,7)->nullable(); $table->timestamps(); $table->softDeletes(); $table->index(['route_id','name']); }
    public function down(): void { foreach (array_reverse(['users','customers','drivers','vehicle_layouts','vehicles','vehicle_seats','seat_maps','routes','pickup_points','drop_points','schedules','trips','bookings','passengers','seat_reservations','tickets','payments','promos','vouchers','pricing_rules','memberships','notifications','activity_logs']) as $t) Schema::dropIfExists($t); }
};
