'use client';

import { clsx } from 'clsx';
import { Bell, Loader2, Plus, Search, WifiOff } from 'lucide-react';
import type { ButtonHTMLAttributes, HTMLAttributes, ReactNode } from 'react';

export function AppCard({ className, ...props }: HTMLAttributes<HTMLElement>) { return <section className={clsx('rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900', className)} {...props} />; }
export function StatsCard({ label, value, helper }: { label: string; value: string; helper?: string }) { return <AppCard><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 font-display text-3xl font-bold">{value}</p>{helper ? <p className="mt-2 text-sm text-slate-500">{helper}</p> : null}</AppCard>; }
export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) { return <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="font-display text-3xl font-bold tracking-tight">{title}</h1>{description ? <p className="mt-2 text-slate-500">{description}</p> : null}</div>{actions}</div>; }
export function SectionHeader({ title, description }: { title: string; description?: string }) { return <div><h2 className="font-display text-xl font-bold">{title}</h2>{description ? <p className="mt-1 text-sm text-slate-500">{description}</p> : null}</div>; }
export function SearchBar({ placeholder = 'Search STMS...', className }: { placeholder?: string; className?: string }) { return <label className={clsx('flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm dark:border-slate-800 dark:bg-slate-950', className)}><Search size={16} className="text-slate-400" /><input aria-label={placeholder} placeholder={placeholder} className="w-full bg-transparent outline-none" /></label>; }
export function FilterBar({ children }: { children?: ReactNode }) { return <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900">{children ?? <span className="text-sm text-slate-500">Filters ready</span>}</div>; }
export function DataTable({ columns, rows }: { columns: string[]; rows?: Array<Array<ReactNode>> }) { return <div className="overflow-hidden rounded-2xl border border-slate-200 dark:border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{columns.map((c) => <th key={c} className="px-4 py-3 font-bold">{c}</th>)}</tr></thead><tbody>{(rows?.length ? rows : [['No data', 'Ready for integration']]).map((row, i) => <tr key={i} className="border-t border-slate-100 dark:border-slate-800">{row.map((cell, j) => <td key={j} className="px-4 py-3 text-slate-600 dark:text-slate-300">{cell}</td>)}</tr>)}</tbody></table></div>; }
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'danger' }) { const tones = { neutral: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200', success: 'bg-green-100 text-green-700', warning: 'bg-amber-100 text-amber-700', danger: 'bg-red-100 text-red-700' }; return <span className={clsx('inline-flex rounded-full px-3 py-1 text-xs font-bold', tones[tone])}>{children}</span>; }
export function Timeline({ items = ['Requested', 'Assigned', 'On trip', 'Completed'] }: { items?: string[] }) { return <ol className="space-y-3">{items.map((item, i) => <li key={item} className="flex gap-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-primary text-xs font-bold text-white">{i + 1}</span><span className="font-semibold">{item}</span></li>)}</ol>; }
export function Drawer({ open, children }: { open?: boolean; children: ReactNode }) { return open ? <aside className="fixed inset-y-0 right-0 z-50 w-80 bg-white p-6 shadow-soft dark:bg-slate-950">{children}</aside> : null; }
export function Modal({ open, title, children }: { open?: boolean; title: string; children: ReactNode }) { return open ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><AppCard className="max-w-lg"><h2 className="font-display text-xl font-bold">{title}</h2><div className="mt-4">{children}</div></AppCard></div> : null; }
export function ConfirmDialog(props: { open?: boolean; title?: string }) { return <Modal open={props.open} title={props.title ?? 'Confirm action'}><p className="text-slate-500">Confirmation UI foundation is ready.</p></Modal>; }
export function Toast({ message }: { message?: string }) { return message ? <div className="fixed bottom-6 right-6 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white shadow-soft">{message}</div> : null; }
export function Loading() { return <div className="flex items-center justify-center gap-2 p-8 text-sm font-bold text-slate-500"><Loader2 className="animate-spin" size={18} /> Loading</div>; }
export function Skeleton({ className }: { className?: string }) { return <div className={clsx('h-24 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800', className)} />; }
export function EmptyState({ title = 'No records yet', description = 'Content will appear here when available.' }) { return <AppCard className="text-center"><Bell className="mx-auto text-slate-400" /><h3 className="mt-4 font-display text-xl font-bold">{title}</h3><p className="mt-2 text-sm text-slate-500">{description}</p></AppCard>; }
export function OfflineState() { return <div className="flex items-center gap-2 rounded-2xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700"><WifiOff size={16} /> You are offline</div>; }
export function ReconnectState() { return <div className="rounded-2xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-700">Reconnecting realtime services...</div>; }
export function ActionButton({ className, ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={clsx('inline-flex items-center justify-center rounded-2xl bg-primary px-4 py-2 text-sm font-bold text-white shadow-sm', className)} {...props} />; }
export function FloatingButton(props: ButtonHTMLAttributes<HTMLButtonElement>) { return <button className="fixed bottom-20 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-primary text-white shadow-soft md:hidden" {...props}><Plus /></button>; }
